[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.12",
    "fastmcp>=2.9.0",
    "jinja2==3.1.6",
    "pandas==2.3.0",
    "posit-sdk==0.10.0",
    "scikit-learn==1.7.0",
]
