[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.12",
    "jinja2==3.1.6",
    "mcp==1.9.3",
    "pandas==2.3.0",
    "posit-sdk==0.10.0",
    "scikit-learn==1.7.0",
]
