name = "prototype-content-with-issues-table"
title = "Content With Issues (table view)"
description = "R Shiny prototype extension that displays a table of all failed content jobs."
access_type = "acl"
