---
title: "Stock Update"
output: blastula::blastula_email
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello Team,

Here are the latest **GSPC** index levels as of `r format(latest_date, "%B %d, %Y")`:

```{r}
price_new <- prices[, c("GSPC.Open", "GSPC.Close")]
colnames(price_new) <- c("open", "close")
price_new$change <- price_new$close - stats::lag(price_new$close, 1)

# include a table with the index levels
format_table(
    x = as.data.frame(tail(price_new)),
    table.attr = 'cellpadding="8" style="border-collapse: collapse;"',
    list(
      change = formatter(
        "span",
        style = x ~ ifelse(
          x > 0,
          formattable::style(color = "green"),
          formattable::style(color = "red")))
    )
  )
```

The historical trend is shown below: 

```{r}
# include a plot with the price data
recent[, "GSPC.Adjusted"] %>%
  autoplot() +
  geom_smooth() +
  theme_fivethirtyeight() +
  labs(
    title = sprintf("%s Adjusted Close", "GSPC")
  )
```

Let me know if you have any questions.


Best,


Team Lead

