# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "pyright",
#     "posit-sdk",
# ]
#
# [tool.uv.sources]
# chatlas = { git = "https://github.com/posit-dev/chatlas", rev = "main" }
# posit-sdk = { git = "https://github.com/posit-dev/posit-sdk-py", rev = "main" }
# ///
from __future__ import annotations

import asyncio
import os
import pathlib
import shutil

import pyright


# # Set working directory to the root of the repository
# repo_root = pathlib.Path(__file__)
# while not os.path.exists(repo_root / "pyproject.toml"):
#     repo_root = repo_root.parent
# os.chdir(repo_root)

here = pathlib.Path(__file__).parent


def cleanup() -> None:
    # Clean slate
    print("Clean up")
    for f in [
        "typings",
        "_repomix-instructions.md",
    ]:
        path = here / f
        if os.path.exists(path):
            print("Removing path:", path.relative_to(here))
            if path.is_dir():
                shutil.rmtree(path)
            else:
                os.remove(path)
    print("--\n")


async def main() -> None:
    # Clean slate
    cleanup()

    print("Creating type stubs: ./typings")
    pyright.run("--createstub", "posit")
    print("--\n")

    print("Trimming type stubs")
    remove_prefix_from_files(
        "typings",
        '"""\nThis type stub file was generated by pyright.\n"""\n\n',
    )
    print("--\n")

    print("Getting Swagger information")
    os.system("python ./_update_swagger.py")

    with open("_repomix-instructions.md", "w") as prompt_f:
        with open("custom-prompt-instructions.md", "r") as instructions_f:
            prompt_f.write(instructions_f.read())

        prompt_f.write("\n")

        with open("_swagger_prompt.md", "r") as swagger_f:
            prompt_f.write(swagger_f.read())
    print("--\n")

    # repomix GitHub Repo: https://github.com/yamadashy/repomix
    # Python alternative: https://pypi.org/project/code2prompt/
    # * Does not contain XML output (suggested by anthropic)
    print("Creating repomix output")
    # Assert npx exists in system
    assert os.system("npx --version") == 0, (
        "npx not found in system. Please install Node.js"
    )
    exit_code = os.system(
        "npx --package repomix --yes repomix --config repomix.config.json --output _prompt.xml typings/posit"
    )
    assert exit_code == 0, "repomix failed to build prompt file: _prompt.xml"
    print("--\n")

    # Clean slate
    cleanup()


def remove_prefix_from_files(folder: str | pathlib.Path, prefix: str) -> None:
    root_folder = pathlib.Path(folder)
    for path in root_folder.rglob("*.pyi"):
        with open(path, "r") as f:
            file_txt = f.read()

        file_txt = file_txt.removeprefix(prefix)

        with open(path, "w") as f:
            f.write(file_txt)


if __name__ == "__main__":
    asyncio.run(main())
