services:
  tests:
    image: ${DOCKER_PROJECT_IMAGE_TAG}
    # Run integration test suite.
    #
    # Target is relative to the ./integration directory, not the project root
    # directory. The execution base directory is determined by the 'WORKDIR'
    # in the Dockerfile.
    command: make test
    environment:
        - CONNECT_BOOTSTRAP_SECRETKEY=${CONNECT_BOOTSTRAP_SECRETKEY}
        # Port 3939 is the default port for Connect
        - CONNECT_SERVER=http://connect:3939
        - CONNECT_VERSION=${CONNECT_VERSION}
        - EXTENSION_NAME=${EXTENSION_NAME}
        - PYTEST_ARGS=${PYTEST_ARGS}
    volumes:
      - .:/connect-extensions/integration
      - ./empty:/connect-extensions/integration/.venv  # Ignore local venv to ensure use of the one in the container
      - ./rstudio-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg:ro
      - ./logs:/var/log/rstudio-connect
    depends_on:
      connect:
        condition: service_healthy
    networks:
      - test

  connect:
    image: ${DOCKER_CONNECT_IMAGE}:${DOCKER_CONNECT_IMAGE_TAG}
    pull_policy: always
    environment:
      - CONNECT_BOOTSTRAP_ENABLED=true
      - CONNECT_BOOTSTRAP_SECRETKEY=${CONNECT_BOOTSTRAP_SECRETKEY}
      - CONNECT_APPLICATIONS_PACKAGEAUDITINGENABLED=true
      - CONNECT_API_KEY  # The API key generated from the Makefile test target
      # Connect configuration overrides https://docs.posit.co/connect/admin/appendix/configuration/#environment-variables
      - CONNECT_SERVER_SENDEREMAIL=no-reply@example.com
      - CONNECT_SERVER_EMAILPROVIDER=SMTP
      - CONNECT_SMTP_HOST=mailhog
      - CONNECT_SMTP_PORT=1025
      - CONNECT_SMTP_TLS=false
      - CONNECT_SMTP_USER=
      - CONNECT_SMTP_PASSWORD=
    depends_on:
      mailhog:
        condition: service_healthy
    ports:
      - "3939:3939"
    networks:
      - test
    privileged: true
    volumes:
      - /var/lib/rstudio-connect
      - ./license.lic:/var/lib/rstudio-connect/rstudio-connect.lic:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3939"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Logs basic email envelope information to stdout, provides an optional UI if you need to read the full messages
  mailhog:
    image: mailhog/mailhog:latest
    container_name: connect-extensions-mailhog
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    networks:
      - test
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8025"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  test:
    driver: bridge
