name: Audit API
on:
  pull_request:
    paths:
      - 'extensions/audit-api/**'

env:
  EXTENSION_NAME: audit-api

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create TAR
        working-directory: ./extensions
        run: tar -czf $EXTENSION_NAME.tar.gz $EXTENSION_NAME

      - name: Upload extension TAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}.tar.gz
          path: extensions/${{ env.EXTENSION_NAME }}.tar.gz
